"""Generate the SQL that re-seeds content_pages from the markdown in the repo.

Run:  python3 scripts/gen-seed-content.py > supabase/migrations/NNNN_<name>.sql

The app never reads markdown — blog posts and docs are served from the
`content_pages` table (see 0021_content_pages.sql), and the markdown under
`content/docs/` and `content/blog/` is the source of record. Editing the
markdown alone therefore does NOT change what users read: this script turns it
into an idempotent migration so the DB copy can be brought back in sync
(precedent: 0027_content_pages_card_copy_reseed.sql, gen-seed-plans.py).

Idempotent by construction: every row is an upsert on (type, slug).
`published` is only set on INSERT — an existing row's visibility is never
flipped here, so a hidden page stays hidden (docs/plans is hidden while
self-serve billing is untested).

The .sql this emits can be large (all docs + posts inline); that is the
existing pattern — 0021 is the same shape.
"""
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent

# (type, slug) rows that must NOT be published when first inserted. Existing
# rows keep whatever `published` they already have.
UNPUBLISHED_ON_INSERT = {("docs", "plans")}

SOURCES = (("blog", "content/blog"), ("docs", "content/docs"))


def parse(path: pathlib.Path) -> dict:
    """Front matter -> fields, body -> content."""
    text = path.read_text()
    _, front, body = text.split("---", 2)

    def field(name: str) -> str | None:
        m = re.search(rf"^{name}:\s*(.+)$", front, re.M)
        return m.group(1).strip() if m else None

    return {
        "title": field("title"),
        "description": field("description") or "",
        "date": field("date"),
        "author": field("author"),
        "tags": field("tags"),
        "content": body.lstrip("\n"),
    }


def lit(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


rows: list[str] = []
for kind, folder in SOURCES:
    for path in sorted((root / folder).glob("*.md")):
        meta = parse(path)
        slug = path.stem
        published = "false" if (kind, slug) in UNPUBLISHED_ON_INSERT else "true"
        # Docs carry no author/date/tags; blog posts do.
        author = meta["author"] if kind == "blog" else None
        date = meta["date"] if kind == "blog" else None
        tags = meta["tags"] if kind == "blog" else None
        rows.append(
            "insert into public.content_pages\n"
            "  (type, slug, title, description, content, author, date, tags, published)\n"
            f"values ({lit(kind)}, {lit(slug)}, {lit(meta['title'])}, "
            f"{lit(meta['description'])}, {lit(meta['content'])}, {lit(author)}, "
            f"{lit(date)}, {lit(tags)}, {published})\n"
            "on conflict (type, slug) do update\n"
            "  set title = excluded.title,\n"
            "      description = excluded.description,\n"
            "      content = excluded.content,\n"
            "      author = excluded.author,\n"
            "      date = excluded.date,\n"
            "      tags = excluded.tags;"
        )

header = """-- Re-seed content_pages from the markdown in content/docs/ and content/blog/.
--
-- Generated by scripts/gen-seed-content.py -- do not edit by hand; rerun the
-- generator instead. The DB copy is what the app serves, so a markdown edit
-- needs this migration to reach users.
--
-- 0021_content_pages.sql stays the source of record for fresh installs; this
-- migration brings environments where the seed has already run back in sync
-- (docs pages had drifted: cards/batch/gallery/version-history copy was missing
-- from the served rows).
--
-- Idempotent: upserts on (type, slug). `published` is set only on INSERT, so
-- docs/plans stays hidden in environments where 0028 already applied.
"""

sys.stdout.write(header + "\n" + "\n\n".join(rows) + "\n")
