import type { FewerNode, FewerEdge } from "./types";
import { getRelativePath } from "./validation";

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function timestamp(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(
    d.getHours()
  )}${pad(d.getMinutes())}`;
}

/* -------------------------------------------------------------------------- */
/*  Directory Script Export                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Generates a shell script (Linux/macOS) or batch script (Windows) with
 * mkdir commands for every folder node in the graph.
 */
export function exportDirectoryScript(
  nodes: FewerNode[],
  edges: FewerEdge[]
) {
  const isWindows =
    typeof navigator !== "undefined" &&
    /Win|Windows/.test(navigator.platform || navigator.userAgent || "");

  // Only generate mkdir for folder nodes
  const folderNodes = nodes.filter((n) => n.data.type === "folder");
  const paths = folderNodes
    .map((n) => getRelativePath(n.id, nodes, edges))
    .filter(Boolean)
    .sort();

  if (isWindows) {
    const lines = [
      "@echo off",
      "REM Generated by fewer",
      `REM ${new Date().toISOString()}`,
      "",
      ...paths.map((p) => `mkdir "${p.replace(/\//g, "\\")}"`),
      "",
      "echo Directory structure created successfully.",
      "pause",
    ];
    downloadBlob(lines.join("\r\n"), `create_folders-${timestamp()}.bat`, "text/plain");
  } else {
    const lines = [
      "#!/bin/bash",
      "# Generated by fewer",
      `# ${new Date().toISOString()}`,
      "",
      ...paths.map((p) => `mkdir -p "${p}"`),
      "",
      'echo "Directory structure created successfully."',
    ];
    downloadBlob(
      lines.join("\n"),
      `create_folders-${timestamp()}.sh`,
      "application/x-sh"
    );
  }
}

/* -------------------------------------------------------------------------- */
/*  Directory Tree TXT Export                                                 */
/* -------------------------------------------------------------------------- */

interface TreeNode {
  node: FewerNode;
  children: TreeNode[];
}

function buildForest(nodes: FewerNode[], edges: FewerEdge[]): TreeNode[] {
  // Roots = folder nodes with no parent edge
  const childMap = new Map<string, string[]>();
  for (const e of edges) {
    const arr = childMap.get(e.source) ?? [];
    arr.push(e.target);
    childMap.set(e.source, arr);
  }

  const hasParent = new Set(edges.map((e) => e.target));
  const roots = nodes.filter((n) => !hasParent.has(n.id));

  function build(nodeId: string, visited: Set<string>): TreeNode | null {
    if (visited.has(nodeId)) return null; // cycle guard
    const node = nodes.find((n) => n.id === nodeId);
    if (!node) return null;
    const nextVisited = new Set(visited);
    nextVisited.add(nodeId);
    const childIds = childMap.get(nodeId) ?? [];
    const children = childIds
      .map((cid) => build(cid, nextVisited))
      .filter((c): c is TreeNode => c !== null);
    // Sort: folders first, then files, alphabetical within each group
    children.sort((a, b) => {
      if (a.node.data.type !== b.node.data.type) {
        return a.node.data.type === "folder" ? -1 : 1;
      }
      return a.node.data.label.localeCompare(b.node.data.label);
    });
    return { node, children };
  }

  return roots
    .map((r) => build(r.id, new Set()))
    .filter((t): t is TreeNode => t !== null)
    .sort((a, b) => {
      if (a.node.data.type !== b.node.data.type) {
        return a.node.data.type === "folder" ? -1 : 1;
      }
      return a.node.data.label.localeCompare(b.node.data.label);
    });
}

function renderTree(tree: TreeNode, prefix: string, isLast: boolean, lines: string[]) {
  const connector = isLast ? "└── " : "├── ";
  const suffix = tree.node.data.type === "folder" ? "/" : "";
  lines.push(`${prefix}${connector}${tree.node.data.label}${suffix}`);
  const childPrefix = prefix + (isLast ? "    " : "│   ");
  tree.children.forEach((child, i) => {
    renderTree(child, childPrefix, i === tree.children.length - 1, lines);
  });
}

/**
 * Generates a Unicode ASCII tree representation of the directory structure
 * and downloads it as directory_tree.txt.
 */
export function exportDirectoryTree(
  nodes: FewerNode[],
  edges: FewerEdge[]
) {
  const forest = buildForest(nodes, edges);
  const lines: string[] = ["Directory Tree Structure", ""];

  forest.forEach((tree, i) => {
    // Root node: no connector, just the name
    const suffix = tree.node.data.type === "folder" ? "/" : "";
    lines.push(`${tree.node.data.label}${suffix}`);
    tree.children.forEach((child, j) => {
      renderTree(child, "", j === tree.children.length - 1, lines);
    });
    if (i < forest.length - 1) lines.push(""); // spacing between roots
  });

  lines.push("");
  downloadBlob(lines.join("\n"), `directory_tree-${timestamp()}.txt`, "text/plain");
}
