import type { CustomTheme, CustomThemeColor } from "./types";

export interface ThemePreset {
  name: string;
  category: string;
  description: string;
  theme: CustomTheme;
}

function c(color: string, opacity: number = 1): CustomThemeColor {
  return { color, opacity };
}

export const THEME_PRESETS: ThemePreset[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // CATPUCCIN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Catppuccin Mocha",
    category: "Catppuccin",
    description: "Dark theme with rich, vibrant pastel colors",
    theme: {
      background: c("#1e1e2e"),
      defaultText: c("#cdd6f4"),
      subtleText: c("#a6adc8"),
      itemHover: c("#cdd6f4", 0.08),
      handle: c("#585b70"),
      edge: c("#585b70", 0.5),
      selectRing: c("#89dceb"),
      folderBg: c("#fab387", 0.15),
      folderText: c("#fab387"),
      folderSubtleText: c("#a6adc8"),
      folderBorder: c("#fab387", 0.45),
      folderIcon: c("#fab387"),
      fileBg: c("#cba6f7", 0.15),
      fileText: c("#cdd6f4"),
      fileSubtleText: c("#a6adc8"),
      fileBorder: c("#cba6f7", 0.45),
      fileIcon: c("#cba6f7"),
    },
  },
  {
    name: "Catppuccin Latte",
    category: "Catppuccin",
    description: "Light theme with warm, cozy pastel colors",
    theme: {
      background: c("#eff1f5"),
      defaultText: c("#4c4f69"),
      subtleText: c("#7c7f93"),
      itemHover: c("#4c4f69", 0.06),
      handle: c("#9ca0b0"),
      edge: c("#9ca0b0", 0.4),
      selectRing: c("#04a5e5"),
      folderBg: c("#fe640b", 0.12),
      folderText: c("#fe640b"),
      folderSubtleText: c("#7c7f93"),
      folderBorder: c("#fe640b", 0.45),
      folderIcon: c("#fe640b"),
      fileBg: c("#8839ef", 0.12),
      fileText: c("#4c4f69"),
      fileSubtleText: c("#7c7f93"),
      fileBorder: c("#8839ef", 0.45),
      fileIcon: c("#8839ef"),
    },
  },
  {
    name: "Catppuccin Frappé",
    category: "Catppuccin",
    description: "Medium-dark theme with balanced contrast",
    theme: {
      background: c("#303446"),
      defaultText: c("#c6d0f5"),
      subtleText: c("#a5adce"),
      itemHover: c("#c6d0f5", 0.08),
      handle: c("#626880"),
      edge: c("#626880", 0.5),
      selectRing: c("#99dbee"),
      folderBg: c("#e5c890", 0.15),
      folderText: c("#e5c890"),
      folderSubtleText: c("#a5adce"),
      folderBorder: c("#e5c890", 0.45),
      folderIcon: c("#e5c890"),
      fileBg: c("#ca9ee6", 0.15),
      fileText: c("#c6d0f5"),
      fileSubtleText: c("#a5adce"),
      fileBorder: c("#ca9ee6", 0.45),
      fileIcon: c("#ca9ee6"),
    },
  },
  {
    name: "Catppuccin Macchiato",
    category: "Catppuccin",
    description: "Dark theme with deeper, richer tones",
    theme: {
      background: c("#24273a"),
      defaultText: c("#cad3f5"),
      subtleText: c("#a5adcb"),
      itemHover: c("#cad3f5", 0.08),
      handle: c("#5b6078"),
      edge: c("#5b6078", 0.5),
      selectRing: c("#91d7e3"),
      folderBg: c("#f4dbd6", 0.15),
      folderText: c("#f4dbd6"),
      folderSubtleText: c("#a5adcb"),
      folderBorder: c("#f4dbd6", 0.45),
      folderIcon: c("#f4dbd6"),
      fileBg: c("#c6a0f6", 0.15),
      fileText: c("#cad3f5"),
      fileSubtleText: c("#a5adcb"),
      fileBorder: c("#c6a0f6", 0.45),
      fileIcon: c("#c6a0f6"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NORD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Nord",
    category: "Nord",
    description: "Arctic, north-bluish clean and elegant theme",
    theme: {
      background: c("#2e3440"),
      defaultText: c("#eceff4"),
      subtleText: c("#d8dee9"),
      itemHover: c("#eceff4", 0.08),
      handle: c("#4c566a"),
      edge: c("#4c566a", 0.5),
      selectRing: c("#81a1c1"),
      folderBg: c("#88c0d0", 0.15),
      folderText: c("#88c0d0"),
      folderSubtleText: c("#d8dee9"),
      folderBorder: c("#88c0d0", 0.45),
      folderIcon: c("#88c0d0"),
      fileBg: c("#b48ead", 0.15),
      fileText: c("#eceff4"),
      fileSubtleText: c("#d8dee9"),
      fileBorder: c("#b48ead", 0.45),
      fileIcon: c("#b48ead"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DRACULA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Dracula",
    category: "Dracula",
    description: "Dark theme with vibrant, gothic-inspired colors",
    theme: {
      background: c("#282a36"),
      defaultText: c("#f8f8f2"),
      subtleText: c("#99b3ff"),
      itemHover: c("#f8f8f2", 0.08),
      handle: c("#44475a"),
      edge: c("#44475a", 0.5),
      selectRing: c("#8be9fd"),
      folderBg: c("#50fa7b", 0.15),
      folderText: c("#50fa7b"),
      folderSubtleText: c("#c8d4f7"),
      folderBorder: c("#50fa7b", 0.45),
      folderIcon: c("#50fa7b"),
      fileBg: c("#bd93f9", 0.15),
      fileText: c("#f8f8f2"),
      fileSubtleText: c("#a9b9e9"),
      fileBorder: c("#bd93f9", 0.45),
      fileIcon: c("#bd93f9"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRUVBOX
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Gruvbox Dark",
    category: "Gruvbox",
    description: "Retro groove dark theme with warm earth tones",
    theme: {
      background: c("#282828"),
      defaultText: c("#ebdbb2"),
      subtleText: c("#928374"),
      itemHover: c("#ebdbb2", 0.08),
      handle: c("#504945"),
      edge: c("#504945", 0.5),
      selectRing: c("#8ec07c"),
      folderBg: c("#b8bb26", 0.15),
      folderText: c("#b8bb26"),
      folderSubtleText: c("#928374"),
      folderBorder: c("#b8bb26", 0.45),
      folderIcon: c("#b8bb26"),
      fileBg: c("#d3869b", 0.15),
      fileText: c("#ebdbb2"),
      fileSubtleText: c("#928374"),
      fileBorder: c("#d3869b", 0.45),
      fileIcon: c("#d3869b"),
    },
  },
  {
    name: "Gruvbox Light",
    category: "Gruvbox",
    description: "Retro groove light theme with warm earth tones",
    theme: {
      background: c("#fbf1c7"),
      defaultText: c("#3c3836"),
      subtleText: c("#7c6f64"),
      itemHover: c("#3c3836", 0.06),
      handle: c("#a89984"),
      edge: c("#a89984", 0.4),
      selectRing: c("#458588"),
      folderBg: c("#98971a", 0.12),
      folderText: c("#98971a"),
      folderSubtleText: c("#7c6f64"),
      folderBorder: c("#98971a", 0.45),
      folderIcon: c("#98971a"),
      fileBg: c("#b16286", 0.12),
      fileText: c("#3c3836"),
      fileSubtleText: c("#7c6f64"),
      fileBorder: c("#b16286", 0.45),
      fileIcon: c("#b16286"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOKYO NIGHT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Tokyo Night",
    category: "Tokyo Night",
    description: "Dark theme inspired by Tokyo's neon lights",
    theme: {
      background: c("#1a1b26"),
      defaultText: c("#c0caf5"),
      subtleText: c("#565f89"),
      itemHover: c("#c0caf5", 0.08),
      handle: c("#414868"),
      edge: c("#414868", 0.5),
      selectRing: c("#7dcfff"),
      folderBg: c("#7aa2f7", 0.15),
      folderText: c("#7aa2f7"),
      folderSubtleText: c("#565f89"),
      folderBorder: c("#7aa2f7", 0.45),
      folderIcon: c("#7aa2f7"),
      fileBg: c("#bb9af7", 0.15),
      fileText: c("#c0caf5"),
      fileSubtleText: c("#565f89"),
      fileBorder: c("#bb9af7", 0.45),
      fileIcon: c("#bb9af7"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ROSE PINE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Rose Pine",
    category: "Rose Pine",
    description: "All-natural, calming dark theme",
    theme: {
      background: c("#191724"),
      defaultText: c("#e0def4"),
      subtleText: c("#6e6a86"),
      itemHover: c("#e0def4", 0.1),
      handle: c("#56526e"),
      edge: c("#56526e", 0.6),
      selectRing: c("#9ccfd8"),
      folderBg: c("#ebbcba", 0.18),
      folderText: c("#ebbcba"),
      folderSubtleText: c("#6e6a86"),
      folderBorder: c("#ebbcba", 0.5),
      folderIcon: c("#ebbcba"),
      fileBg: c("#c4a7e7", 0.18),
      fileText: c("#e0def4"),
      fileSubtleText: c("#6e6a86"),
      fileBorder: c("#c4a7e7", 0.5),
      fileIcon: c("#c4a7e7"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SOLARIZED
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Solarized Dark",
    category: "Solarized",
    description: "Precision-crafted dark theme for screens",
    theme: {
      background: c("#002b36"),
      defaultText: c("#839496"),
      subtleText: c("#b6dfee"),
      itemHover: c("#839496", 0.08),
      handle: c("#586e75"),
      edge: c("#586e75", 0.5),
      selectRing: c("#268bd2"),
      folderBg: c("#2aa198", 0.15),
      folderText: c("#2aa198"),
      folderSubtleText: c("#b7ddeb"),
      folderBorder: c("#2aa198", 0.45),
      folderIcon: c("#2aa198"),
      fileBg: c("#6c71c4", 0.15),
      fileText: c("#839496"),
      fileSubtleText: c("#b7ddeb"),
      fileBorder: c("#6c71c4", 0.45),
      fileIcon: c("#6c71c4"),
    },
  },
  {
    name: "Solarized Light",
    category: "Solarized",
    description: "Precision-crafted light theme for screens",
    theme: {
      background: c("#fdf6e3"),
      defaultText: c("#657b83"),
      subtleText: c("#353b3b"),
      itemHover: c("#657b83", 0.06),
      handle: c("#93a1a1"),
      edge: c("#93a1a1", 0.4),
      selectRing: c("#268bd2"),
      folderBg: c("#2aa198", 0.12),
      folderText: c("#2aa198"),
      folderSubtleText: c("#353b3b"),
      folderBorder: c("#2aa198", 0.45),
      folderIcon: c("#2aa198"),
      fileBg: c("#6c71c4", 0.12),
      fileText: c("#657b83"),
      fileSubtleText: c("#353b3b"),
      fileBorder: c("#6c71c4", 0.45),
      fileIcon: c("#6c71c4"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ONE DARK / ONE LIGHT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "One Dark",
    category: "One",
    description: "Atom editor inspired dark theme",
    theme: {
      background: c("#282c34"),
      defaultText: c("#abb2bf"),
      subtleText: c("#a8b5cd"),
      itemHover: c("#abb2bf", 0.08),
      handle: c("#3e4451"),
      edge: c("#3e4451", 0.5),
      selectRing: c("#56b6c2"),
      folderBg: c("#98c379", 0.15),
      folderText: c("#98c379"),
      folderSubtleText: c("#abb7cf"),
      folderBorder: c("#98c379", 0.45),
      folderIcon: c("#98c379"),
      fileBg: c("#c678dd", 0.15),
      fileText: c("#abb2bf"),
      fileSubtleText: c("#bdcbe4"),
      fileBorder: c("#c678dd", 0.45),
      fileIcon: c("#c678dd"),
    },
  },
  {
    name: "One Light",
    category: "One",
    description: "Atom editor inspired light theme",
    theme: {
      background: c("#fafafa"),
      defaultText: c("#383a42"),
      subtleText: c("#4e4e52"),
      itemHover: c("#383a42", 0.06),
      handle: c("#c0c0c0"),
      edge: c("#c0c0c0", 0.4),
      selectRing: c("#0184bc"),
      folderBg: c("#50a14f", 0.12),
      folderText: c("#50a14f"),
      folderSubtleText: c("#4e4e52"),
      folderBorder: c("#50a14f", 0.45),
      folderIcon: c("#50a14f"),
      fileBg: c("#a626a4", 0.12),
      fileText: c("#383a42"),
      fileSubtleText: c("#4e4e52"),
      fileBorder: c("#a626a4", 0.45),
      fileIcon: c("#a626a4"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GITHUB PRIMER
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "GitHub Dark",
    category: "GitHub",
    description: "GitHub's dark design system palette",
    theme: {
      background: c("#0d1117"),
      defaultText: c("#c9d1d9"),
      subtleText: c("#ccd8e6"),
      itemHover: c("#c9d1d9", 0.08),
      handle: c("#21262d"),
      edge: c("#21262d", 0.5),
      selectRing: c("#58a6ff"),
      folderBg: c("#3fb950", 0.15),
      folderText: c("#3fb950"),
      folderSubtleText: c("#ccd8e6"),
      folderBorder: c("#3fb950", 0.45),
      folderIcon: c("#3fb950"),
      fileBg: c("#a371f7", 0.15),
      fileText: c("#c9d1d9"),
      fileSubtleText: c("#ccd8e6"),
      fileBorder: c("#a371f7", 0.45),
      fileIcon: c("#a371f7"),
    },
  },
  {
    name: "GitHub Light",
    category: "GitHub",
    description: "GitHub's light design system palette",
    theme: {
      background: c("#ffffff"),
      defaultText: c("#24292f"),
      subtleText: c("#57606a"),
      itemHover: c("#24292f", 0.06),
      handle: c("#d0d7de"),
      edge: c("#d0d7de", 0.4),
      selectRing: c("#0969da"),
      folderBg: c("#2da44e", 0.12),
      folderText: c("#2da44e"),
      folderSubtleText: c("#57606a"),
      folderBorder: c("#2da44e", 0.45),
      folderIcon: c("#2da44e"),
      fileBg: c("#8250df", 0.12),
      fileText: c("#24292f"),
      fileSubtleText: c("#57606a"),
      fileBorder: c("#8250df", 0.45),
      fileIcon: c("#8250df"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MATERIAL DESIGN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Material Dark",
    category: "Material",
    description: "Google Material Design dark theme",
    theme: {
      background: c("#121212"),
      defaultText: c("#ffffff"),
      subtleText: c("#b0b0b0"),
      itemHover: c("#ffffff", 0.08),
      handle: c("#2c2c2c"),
      edge: c("#2c2c2c", 0.5),
      selectRing: c("#64ffda"),
      folderBg: c("#bb86fc", 0.15),
      folderText: c("#bb86fc"),
      folderSubtleText: c("#b0b0b0"),
      folderBorder: c("#bb86fc", 0.45),
      folderIcon: c("#bb86fc"),
      fileBg: c("#03dac6", 0.15),
      fileText: c("#ffffff"),
      fileSubtleText: c("#b0b0b0"),
      fileBorder: c("#03dac6", 0.45),
      fileIcon: c("#03dac6"),
    },
  },
  {
    name: "Material Light",
    category: "Material",
    description: "Google Material Design light theme",
    theme: {
      background: c("#ffffff"),
      defaultText: c("#212121"),
      subtleText: c("#757575"),
      itemHover: c("#212121", 0.06),
      handle: c("#bdbdbd"),
      edge: c("#bdbdbd", 0.4),
      selectRing: c("#018786"),
      folderBg: c("#6200ee", 0.12),
      folderText: c("#6200ee"),
      folderSubtleText: c("#757575"),
      folderBorder: c("#6200ee", 0.45),
      folderIcon: c("#6200ee"),
      fileBg: c("#03dac6", 0.12),
      fileText: c("#212121"),
      fileSubtleText: c("#757575"),
      fileBorder: c("#03dac6", 0.45),
      fileIcon: c("#03dac6"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GALLERY STARTER THEMES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Terminal Amber",
    category: "Gallery",
    description: "Dark CRT amber glow for cold code reading",
    theme: {
      background: c("#0d0b07"),
      defaultText: c("#ffe8cc"),
      subtleText: c("#b08968"),
      itemHover: c("#ffd8a8", 0.08),
      handle: c("#7f5539"),
      edge: c("#b08968", 0.45),
      selectRing: c("#ffd43b"),
      folderBg: c("#f08c00", 0.16),
      folderText: c("#ffc078"),
      folderSubtleText: c("#b08968"),
      folderBorder: c("#f08c00", 0.5),
      folderIcon: c("#ffa94d"),
      fileBg: c("#ffd43b", 0.14),
      fileText: c("#ffe8cc"),
      fileSubtleText: c("#b08968"),
      fileBorder: c("#ffd43b", 0.45),
      fileIcon: c("#ffd43b"),
    },
  },
  {
    name: "Blueprint",
    category: "Gallery",
    description: "Light drafting-table blue for technical diagrams",
    theme: {
      background: c("#f1f5fb"),
      defaultText: c("#0b2545"),
      subtleText: c("#4a6fa5"),
      itemHover: c("#0b2545", 0.05),
      handle: c("#94a9c9"),
      edge: c("#4a6fa5", 0.4),
      selectRing: c("#1c7ed6"),
      folderBg: c("#1c7ed6", 0.1),
      folderText: c("#1864ab"),
      folderSubtleText: c("#4a6fa5"),
      folderBorder: c("#1c7ed6", 0.4),
      folderIcon: c("#1c7ed6"),
      fileBg: c("#7048e8", 0.08),
      fileText: c("#0b2545"),
      fileSubtleText: c("#4a6fa5"),
      fileBorder: c("#7048e8", 0.35),
      fileIcon: c("#7048e8"),
    },
  },
  {
    name: "Ink & Clay",
    category: "Gallery",
    description: "Warm editorial light for brand decks",
    theme: {
      background: c("#faf7f2"),
      defaultText: c("#2b2118"),
      subtleText: c("#7d6b5d"),
      itemHover: c("#2b2118", 0.05),
      handle: c("#b5a392"),
      edge: c("#7d6b5d", 0.4),
      selectRing: c("#e8590c"),
      folderBg: c("#e8590c", 0.12),
      folderText: c("#d9480f"),
      folderSubtleText: c("#7d6b5d"),
      folderBorder: c("#e8590c", 0.45),
      folderIcon: c("#e8590c"),
      fileBg: c("#5f3dc4", 0.1),
      fileText: c("#2b2118"),
      fileSubtleText: c("#7d6b5d"),
      fileBorder: c("#5f3dc4", 0.4),
      fileIcon: c("#7048e8"),
    },
  },
  {
    name: "Neon Grid",
    category: "Gallery",
    description: "Dark synth for dense nodes and neon accents",
    theme: {
      background: c("#0a0b12"),
      defaultText: c("#e6e9f5"),
      subtleText: c("#8b93b0"),
      itemHover: c("#22d3ee", 0.08),
      handle: c("#3a4260"),
      edge: c("#22d3ee", 0.3),
      selectRing: c("#f472b6"),
      folderBg: c("#22d3ee", 0.14),
      folderText: c("#67e8f9"),
      folderSubtleText: c("#8b93b0"),
      folderBorder: c("#22d3ee", 0.5),
      folderIcon: c("#22d3ee"),
      fileBg: c("#a78bfa", 0.16),
      fileText: c("#ddd6fe"),
      fileSubtleText: c("#8b93b0"),
      fileBorder: c("#a78bfa", 0.5),
      fileIcon: c("#a78bfa"),
    },
  },
  {
    name: "Mono Print",
    category: "Gallery",
    description: "Grayscale for clean export and print",
    theme: {
      background: c("#ffffff"),
      defaultText: c("#111318"),
      subtleText: c("#6b7280"),
      itemHover: c("#111318", 0.04),
      handle: c("#9ca3af"),
      edge: c("#6b7280", 0.5),
      selectRing: c("#111318"),
      folderBg: c("#111318", 0.06),
      folderText: c("#111318"),
      folderSubtleText: c("#6b7280"),
      folderBorder: c("#111318", 0.35),
      folderIcon: c("#374151"),
      fileBg: c("#6b7280", 0.07),
      fileText: c("#111318"),
      fileSubtleText: c("#6b7280"),
      fileBorder: c("#6b7280", 0.3),
      fileIcon: c("#6b7280"),
    },
  },
  {
    name: "Canopy",
    category: "Gallery",
    description: "Dark forest green for media and archive trees",
    theme: {
      background: c("#0a1410"),
      defaultText: c("#d8f3dc"),
      subtleText: c("#86b39b"),
      itemHover: c("#b7e4c7", 0.07),
      handle: c("#3d5c4c"),
      edge: c("#86b39b", 0.4),
      selectRing: c("#63e6be"),
      folderBg: c("#2f9e44", 0.16),
      folderText: c("#8ce99a"),
      folderSubtleText: c("#86b39b"),
      folderBorder: c("#2f9e44", 0.5),
      folderIcon: c("#51cf66"),
      fileBg: c("#63e6be", 0.12),
      fileText: c("#d8f3dc"),
      fileSubtleText: c("#86b39b"),
      fileBorder: c("#63e6be", 0.45),
      fileIcon: c("#63e6be"),
    },
  },
  {
    name: "Aurora Depth",
    category: "Gallery",
    description: "Dark gradients for depth-map aesthetics",
    theme: {
      background: c("#0b1220"),
      defaultText: c("#e7ecf5"),
      subtleText: c("#8fa3c0"),
      itemHover: c("#64d2ff", 0.07),
      handle: c("#3c5378"),
      edge: c("#8fa3c0", 0.35),
      selectRing: c("#a5d8ff"),
      folderBg: c("#4dabf7", 0.14),
      folderText: c("#a5d8ff"),
      folderSubtleText: c("#8fa3c0"),
      folderBorder: c("#4dabf7", 0.45),
      folderIcon: c("#74c0fc"),
      fileBg: c("#9775fa", 0.14),
      fileText: c("#e5dbff"),
      fileSubtleText: c("#8fa3c0"),
      fileBorder: c("#9775fa", 0.45),
      fileIcon: c("#b197fc"),
    },
  },
  {
    name: "Slate Highlighter",
    category: "Gallery",
    description: "Light neutral with strong selection ring for annotated docs",
    theme: {
      background: c("#f8f9fb"),
      defaultText: c("#1b1d22"),
      subtleText: c("#6f7684"),
      itemHover: c("#1b1d22", 0.05),
      handle: c("#a6adbb"),
      edge: c("#6f7684", 0.45),
      selectRing: c("#d6336c"),
      folderBg: c("#f59f00", 0.14),
      folderText: c("#b26a00"),
      folderSubtleText: c("#6f7684"),
      folderBorder: c("#f59f00", 0.45),
      folderIcon: c("#f59f00"),
      fileBg: c("#4c6ef5", 0.1),
      fileText: c("#1b1d22"),
      fileSubtleText: c("#6f7684"),
      fileBorder: c("#4c6ef5", 0.4),
      fileIcon: c("#4c6ef5"),
    },
  },
];